### ISSUE TITLE
Is Editly CPU-bound or GPU-bound?

### ISSUE THREAD

**Issue by nabilfreeman** [mifi/editly#116]
- [x] I have tried with the newest version of editly: `npm i -g editly` or `npm i editly@latest`
- [x] I have tried ffmpeg newest stable version
- [x] I have searched for existing issues

Hi there, in the interest of speeding up renders I tried changing the `ffmpeg` encoder to `h264_videotoolbox` to take advantage of my Mac's GPU. I didn't see much difference. After thinking for a while I believe it's because most of the processing is actually happening at CPU level inside Fabric.

Is that correct or should I expect better performance with hardware encoding?

Also I'm wondering if there is an exponential relationship with the number of layers and render times.

If I merged layers down to several intermediate files would I get better overall performance? I'm planning to try this anyway on next hack day but any advice would be appreciated before then.

Thanks, Nabs

**Comment by mifi** [comment]
hi. it is defibnitely CPU bound. most of the things are happening inside fabric and node-canvas, which is quite slow (especially on large resolutions).

I cannot imagine why there would be an exponential relationship between number of layers and render times, but rather I think there would be a linear relationship.

I've been thinking about making a html based editly, which I think would be a lot faster because browsers use a lot of hardwar eacceleration for its operations, but didnt have time yet.

**Comment by nabilfreeman** [comment]
Thanks for your answer! Very helpful and I'll do further research into Canvas on Node.js. Currently to render out a 1080p video render times are approximately 1:1 with the duration of the video. I'm experimenting with automated podcasting vids (inspiration: Magnet) and some samples are up to an hour in duration, limiting Editly's scalability. I think there is enormous potential here though, so anything interesting I find, will follow up.

**Comment by twicer-is-coder** [comment]
is there any update on this? is there any way to use GPU with editly?
