### ISSUE TITLE
Option to inherit video resolution

### ISSUE THREAD

**Issue by pixelzerg** [mifi/editly#13]
Good work on this project.

Using the CLI, I am concatenating two video files like so
```
editly first_file.mp4 second_file.mp4 --out output.mp4
```

The input files are both 1920x1080, but the resulting video file is 640x360

Specifying the width and height in the command works, however, providing an option to automatically detect the lowest common resolution from the input files would be a good enhancement

**Comment by mifi** [comment]
Yea, I default to a width of 640, because with bigger resolutions it tends to take a longer time to process. I wanted the default command line to produce something relatively quickly, and if people want a higher resolution they can just add parameters.

I could find the lowest common resolution, but I'm not sure how to define lowest common, is it width multiplied by height? as in number of total pixels? Then the output aspect ratio will depend on the aspect ratio of the smallest video (in term of n pixels)

**Comment by pixelzerg** [comment]
Actually, maybe you could just inherit the resolution of the first video provided

**Comment by mifi** [comment]
Yes, but I think most people don't really need full 4K resolution output, and if they do, it's easy to just specify it. I find it more important that it generates a video relatively quickly for first time users

**Comment by chapmanjacobd** [comment]
maybe one solution could be that we put `--fast` in all the examples so that it is fast for first time users but we could default to a compromise resolution like 720p

**Comment by mifi** [comment]
That's a good idea. I will do that

**Comment by gunar** [comment]
I wish `width` and `height` would still override resolution inheritance, even with `fast: true`, because otherwise I have no way to test that my elements are correctly positioned, other than running it with `fast: false`—which defeats the purpose of having a preview option. FYI I'm cropping a vertical video down to a square.

**Comment by mifi** [comment]
Maybe we could instead preserve aspect ratio with fast: true, and make sure the total number of pixels is quite low.

**Comment by mifi** [comment]
Now --fast will keep the aspect ratio, just make the video smaller (62500 pixels)
