### ISSUE TITLE
Multiple audio sources

### ISSUE THREAD

**Issue by fmmsilva** [mifi/editly#62]
Is it possible?

**Comment by mifi** [comment]
I'm not sure what you mean by that

**Comment by fmmsilva** [comment]
I need to add multiple audio files at different points in time

**Comment by mifi** [comment]
That is currently not possible. But you can add one audio file for each clip separately.

**Comment by patcon** [comment]
Should this be closed now?

Also, thank you SO much @mifi -- really inspired by this project. I can imagine a world where something like this helps FOSS projects maintain very user-friendly videos in the same way that TravisCI helps democratize testing. Basically, I could see it helping open source compete better with closed solutions, since supporting users in ways like this is one of the places where businesses run circles around FOSS :)

Speaking of which, know of anyone working on a GitHub Action for generating videos for github releases?

**Comment by mifi** [comment]
Automated video generation by CI is a cool idea!
It's currently not possible to add multiple audio sources at arbitrary times, but possible to add audio per clip

**Comment by mifi** [comment]
Oops i forgot I already implemented [arbitrary audio](https://github.com/mifi/editly#arbitrary-audio-tracks)
